image: condaforge/linux-anvil:latest

test:
  stage: test
  tags:
    - elaspic
  script:
    - conda env create -f environment.yml -n elaspic_webserver -q --force
    - source activate elaspic_webserver
    - flake8
    - py.test

deploy:
  stage: deploy
  tags:
    - elaspic_webserver
  environment:
    name: production
    url: http://elaspic.kimlab.org
  # only:
  #   - master
  script:
    - STAGING_DIR=/home/kimadmin/mum_test
    - rm -rf ${STAGING_DIR}
    - cp -a . ${STAGING_DIR}
    - cd ${STAGING_DIR}
    - ./devtools/gitlab-ci/sentry_release.sh
    - conda env create -f environment.yml -n elaspic_webserver_test -q --force
    - source activate elaspic_webserver_test
    - py.test
