image: condaforge/linux-anvil:latest

stages:
  - test
  - deploy

# === Variables ===

variables:
  PACKAGE_VERSION: 0.0.6

# === Build ===

test:
  stage: test
  tags:
    - local
  before_script:
    - conda config --add channels ostrokach-forge
    - conda config --append channels kimlab
  script:
    - conda env create -f environment.yml -n elaspic_webserver -q --force
    - source activate elaspic_webserver
    - pip install flake8 pytest pytest-asyncio pytest-logging
    - flake8
    - py.test

# === Deploy ===

deploy-prod:
  stage: deploy
  tags:
    - local
  environment:
    name: production
    url: http://elaspic.kimlab.org
  only:
    - master
  script:
    - ./devtools/gitlab-ci/sentry_release.sh
    - STAGING_URL="kimadmin@192.168.6.53"
    - STAGING_DIR="/home/kimadmin/mum_test"
    - rsync -av ./ ${STAGING_URL}:${STAGING_DIR}/
    - ssh ${STAGING_URL}
      "conda env create -f ${STAGING_DIR}/environment.yml -n elaspic_webserver_test -q --force"
