image: condaforge/linux-anvil:latest

test:
  stage: test
  tags:
    - elaspic
  script:
    - conda env create -f environment.yml -n elaspic_webserver -q --force
    - source activate elaspic_webserver
    - py.test
    - flake8

deploy:
  stage: deploy
  tags:
    - elaspic_webserver
  environment:
    name: production
    url: http://elaspic.kimlab.org
  # only:
  #   - master
  script:
    - echo "Deploying..."
    - ./devtools/sentry_release.sh
    - conda env create -f environment.yml -n elaspic_webserver_test -q --force
    - source activate elaspic_webserver_test
    - py.test
