image: condaforge/linux-anvil:latest

stages:
  - test
  - deploy

# === Variables ===

variables:
  PACKAGE_VERSION: 0.0.7

.configure_ssh: &configure_ssh
  before_script:
    # Configure ssh
    - 'which ssh-agent || ( yum update -y -q && yum install openssh-clients.x86_64 -y -q )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'

# === Build ===

test:
  stage: test
  tags:
    - local
  variables:
    DJANGO_SETTINGS_MODULE: mum.settings.pytest
  <<: [*configure_ssh]
  script:
    # Add conda channels
    - conda config --add channels ostrokach-forge
    - conda config --append channels kimlab
    # Install the elaspic-webserver environment
    - conda env create -f environment.yml -n elaspic-webserver -q --force
    - source activate elaspic-webserver
    # Install packages required for testing
    - pip install flake8 pytest pytest-asyncio pytest-logging pytest-cov codecov
    # Test
    - flake8
    - ls -al /home/kimlab1/database_data
    - python elaspic_rest_api/app.py &
    - sleep 30  # give some time for the jobsubmitter to configure itself
    - py.test
    - kill %1  # stop jobsubmitter
    - codecov -t $CODECOV_TOKEN
    - if [[ $CI_COMMIT_REF_NAME == 'master' ]] ; then ./devtools/gitlab-ci/sentry_release.sh ; fi
  coverage: /^TOTAL.*(\d+\%)/

# === Deploy ===

deploy-prod:
  stage: deploy
  tags:
    - local
  environment:
    name: production
    url: http://elaspic.kimlab.org
  variables:
    STAGING_URL: kimadmin@192.168.6.53
    STAGING_DIR: /home/kimadmin/elaspic-webserver
    STAGING_CONDA: /home/kimadmin/miniconda/bin/conda
  <<: [*configure_ssh]
  script:
    # Sync deployment server
    - ssh ${STAGING_URL} "cd $STAGING_DIR && git pull"
    - ssh ${STAGING_URL} "$STAGING_CONDA config --add channels ostrokach-forge"
    - ssh ${STAGING_URL} "$STAGING_CONDA config --append channels kimlab"
    - ssh ${STAGING_URL} "$STAGING_CONDA env create -f ${STAGING_DIR}/environment.yml -n elaspic-webserver -q --force"
    - echo "You must run `./provision.sh' on the deployment server to finish installation"
  only:
    - master
