image: condaforge/linux-anvil:latest

stages:
  - test
  - deploy

# === Variables ===

variables:
  PACKAGE_VERSION: 0.0.7.dev0

# === Build ===

test:
  stage: test
  tags:
    - local
  variables:
    - DJANGO_SETTINGS_MODULE: mum.settings.pytest
  before_script:
    - conda config --add channels ostrokach-forge
    - conda config --append channels kimlab
    - conda env create -f environment.yml -n elaspic_webserver -q --force
    - source activate elaspic_webserver
  script:
    - pip install flake8 pytest pytest-asyncio pytest-logging pytest-cov
    - flake8
    - python elaspic_rest_api/app.py &
    - py.test
    - codecov -t $CODECOV_TOKEN



# === Deploy ===

deploy-prod:
  stage: deploy
  tags:
    - local
  environment:
    name: production
    url: http://elaspic.kimlab.org
  only:
    - master
  script:
    - ./devtools/gitlab-ci/sentry_release.sh
    - STAGING_URL="kimadmin@192.168.6.53"
    - STAGING_DIR="/home/kimadmin/mum_test"
    - rsync -av ./ ${STAGING_URL}:${STAGING_DIR}/
    - ssh ${STAGING_URL}
      "conda env create -f ${STAGING_DIR}/environment.yml -n elaspic_webserver_test -q --force"
