image: condaforge/linux-anvil:latest

build:
  stage: build
  script:
    - conda env create -f environment.yml -n elaspic_webserver -q --force
    - source activate elaspic_webserver

test:
  stage: test
  script:
    - echo "$PATH"
    - py.test

deploy:
  stage: deploy
  only:
    - master
  script:
    - |
      echo "Deploying..."
      curl https://api.rollbar.com/api/1/deploy/ \
        -F access_token="b9f0b75f30fc4de6ba04c7933a1a11b8" \
        -F environment="production" \
        -F revision=`git log -n 1 --pretty=format:"%H"` \
        -F local_username=`whoami`
