[tool.black]
line-length = 100
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | .conda
)/
'''

[tool.isort]
line_length = 100
skip = "docs,__init__.py,setup.py,.gitlab,.conda,env"
default_section = "THIRDPARTY"
known_first_party = "elaspic_rest_api"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
