# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='coremutationlocal',
            index_together=set([('protein_id', 'mut')]),
        ),
        migrations.AlterIndexTogether(
            name='mut',
            index_together=set([('protein', 'mut')]),
        ),
    ]
