# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_pipeline", "0002_auto_20160905_2052"),
    ]

    operations = [
        migrations.AddField(
            model_name="coremutationlocal",
            name="elaspic_version",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
