#!/bin/bash -il

# Copied from: https://github.com/conda-forge/docker-images/blob/master/scripts/entrypoint

# Use non-interactive cp
# unalias cp

# Create conda user with the same uid as the host, so the container can write
# to mounted volumes
# Adapted from https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
USER_ID=${HOST_USER_ID:-9001}
GROUP_ID=${HOST_GROUP_ID:-9001}
id elaspic
groupadd -g ${GROUP_ID} elaspic
useradd --shell /bin/bash -u ${USER_ID} -g elaspic -G conda -o -c "" -m elaspic
export HOME=/home/elaspic
export USER=elaspic
export LOGNAME=elaspic
export MAIL=/var/spool/mail/elaspic
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/elaspic/bin
export supkg="su-exec"
chown elaspic:elaspic $HOME
cp -R /etc/skel $HOME && chown -R elaspic:elaspic $HOME/skel && (ls -A1 $HOME/skel | xargs -I {} mv -n $HOME/skel/{} $HOME) && rm -Rf $HOME/skel

# cp /root/.condarc $HOME/.condarc && chown conda:conda $HOME/.condarc
cd $HOME

# Activate the `base` conda environment.
source /opt/conda/etc/profile.d/conda.sh
conda activate app

# Copy script files
chown elaspic:elaspic -R /staticfiles
chmod ug+rwX -R /staticfiles
/opt/conda/bin/$supkg elaspic manage.py collectstatic --noinput -i download -i jobs

# Run whatever the user wants
exec /opt/conda/bin/$supkg elaspic "$@"
